#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec rake test

if [[ $TRAVIS_BRANCH == 'master' ]]
then
  git config user.name "Travis CI"
  git config user.email "vince.friedling@gmail.com"
  git commit -m "Deployed to Github Pages" -- _site
  git subtree push --prefix _site "https://${GH_TOKEN}@${GH_REF}" gh-pages > /dev/null 2>&1
fi
